from __future__ import annotations

from pathlib import Path
from typing import List

ATTRIBUTES = (
    "origin",
    "purpose",
    "definition",
    "function",
    "main goal",
    "age",
    "name",
    "founder",
    "owner",
    "value",
    "importance",
    "reputation",
    "impact",
    "influence",
    "location",
    "history",
    "status",
    "category",
    "type",
    "meaning",
    "significance",
    "role",
    "date of creation",
    "latest update",
    "duration",
    "size",
    "popularity",
    "main activity",
    "scope",
    "reach",
    "composition",
    "structure",
    "method",
    "strategy",
    "goal",
    "objective",
    "result",
    "effect",
    "outcome",
    "cause",
    "reason",
    "source",
    "destination",
    "trend",
    "main challenge",
    "opinion",
    "leading opinion",
    "common perception",
    "definition in law",
    "ethical standing",
    "main criticism",
    "key advantage",
    "key disadvantage",
    "limitation",
    "potential",
    "likelihood",
    "probability",
    "risk",
    "opportunity",
    "threat",
    "strength",
    "weakness",
    "main competitor",
    "main supporter",
    "main opponent",
    "relationship with others",
    "relevance",
    "timing",
    "frequency",
    "pattern",
    "cost",
    "budget",
    "revenue",
    "profit",
    "loss",
    "market share",
    "demographic",
    "representation",
    "policy",
    "regulation",
    "requirement",
    "recommendation",
    "limiting factor",
    "resource",
    "technology used",
    "process",
    "legal status",
    "acceptance",
    "approval",
    "recognition",
    "symbolism",
    "associations",
    "link to current events",
    "precedent",
    "measurement",
    "ranking",
    "priority",
    "main feature",
    "unique aspect",
    "distinguishing factor",
)


def entity_questions(entity_name: str) -> List[str]:
    return [f"The {p} of {entity_name}" for p in ATTRIBUTES]


def load_generic_prompts(path: str | Path) -> List[str]:
    path = Path(path)
    lines = [l.strip() for l in path.read_text().splitlines() if l.strip()]
    return lines
